### ISSUE TITLE
Update unlogged navigator bar & create logged navigator bar

### ISSUE THREAD

**Issue by bellabaohaha** [Misoto22/Paw-Forum#36]
For unlogged navigator bar: 
Remove sign up button
Add link in log in page to sign up page

Create logged navigator bar: 
Add a profile icon
Add create post button link to create post page

**Comment by sheldonyxd** [comment]
Some more modifications should be noted:
add username in Profile page, 
allow for change avatar,
overlapped create and avatar button.
